# Generated by Django 5.0.2 on 2024-02-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=3)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('position_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.jobposition')),
            ],
        ),
    ]
